#ifndef DX11_SIMPLE_RNDRD_CONSTANTS_INCLUDED
#define DX11_SIMPLE_RNDRD_CONSTANTS_INCLUDED

#define LIGHTS_MAX_COUNT 64
#define LIGHTS_DATA_MAX_SIZE  1024 // max vectors count to represent lights data

#define CONVERT_SRGB_INPUT_TO_LINEAR
#define CONVERT_LINEAR_OUTPUT_TO_SRGB

//#define SIMPLE_RENDER_MODE

#endif // !DX11_SIMPLE_RNDRD_CONSTANTS_INCLUDED
